language: python
python:
    - "3.6"
dist: trusty
sudo: required
services:
  - docker
before_install:
  - docker pull jenkins/jenkins:lts
install:
  - pip install -r requirements.txt
script:
  - pytest tests
notifications:
  email:
  - stollenwerk@kitconcept.com
